name: off_the_map
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_map: ^0.6.1+2
  http: any
  carousel_slider: ^1.3.0
  provider: ^3.0.0+1
  zefyr: ^0.6.0
  cloud_firestore: ^0.12.5+2
  firebase_auth: ^0.11.1+12
  modal_progress_hud: ^0.1.3
  firebase_storage: ^3.0.4
  firebase_core: ^0.4.0+8
  uuid: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true